export const FilterLogicalOperator = {
  OPERATOR_UNSPECIFIED : 'OPERATOR_UNSPECIFIED',
  OR : 'OR',
  AND : 'AND',
}

export const Operator = {
  OPERATOR_UNSPECIFIED : 'OPERATOR_UNSPECIFIED',
  REGEXP : 'REGEXP',
  BEGINS_WITH : 'BEGINS_WITH',
  ENDS_WITH : 'ENDS_WITH',
  PARTIAL : 'PARTIAL',
  EXACT : 'EXACT',
  NUMERIC_EQUAL : 'NUMERIC_EQUAL',
  NUMERIC_GREATER_THAN : 'NUMERIC_GREATER_THAN',
  NUMERIC_LESS_THAN : 'NUMERIC_LESS_THAN',
  IN_LIST : 'IN_LIST',
}

export const CohortType = {
  UNSPECIFIED_COHORT_TYPE : 'UNSPECIFIED_COHORT_TYPE',
  FIRST_VISIT_DATE : 'FIRST_VISIT_DATE',
}
